//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exportdataprocessing
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public string id { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public string @params { get; set; }
        public Nullable<int> month_sales_count { get; set; }
        public Nullable<int> stock { get; set; }
        public Nullable<int> skunumber { get; set; }
        public string shipping_address { get; set; }
        public string shop_id { get; set; }
        public string category_id { get; set; }
        public Nullable<int> comments_count { get; set; }
        public string keyword { get; set; }
        public Nullable<decimal> current_price_min { get; set; }
        public Nullable<decimal> current_price_max { get; set; }
        public Nullable<decimal> original_price_min { get; set; }
        public Nullable<decimal> original_price_max { get; set; }
        public Nullable<int> stores_count { get; set; }
        public Nullable<decimal> score { get; set; }
        public string uri { get; set; }
    }
}
