//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exportdataprocessing
{
    using System;
    using System.Collections.Generic;
    
    public partial class products
    {
        public string id { get; set; }
        public string url { get; set; }
        public string title { get; set; }
        public int skunum { get; set; }
        public decimal minprice { get; set; }
        public decimal maxprice { get; set; }
        public int minchengjiao { get; set; }
        public int minyishou { get; set; }
        public int review_quantity { get; set; }
        public string keyword { get; set; }
        public string market { get; set; }
    }
}
