//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exportdataprocessing
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class YIyilanDatabaseContainer : DbContext
    {
        public YIyilanDatabaseContainer()
            : base("name=YIyilanDatabaseContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<imagedetail> imagedetail { get; set; }
        public virtual DbSet<productparams> productparams { get; set; }
        public virtual DbSet<products> products { get; set; }
        public virtual DbSet<productskus> productskus { get; set; }
        public virtual DbSet<shops> shops { get; set; }
    }
}
